version: "3"

services:
  web:
    container_name: python-${PROJECT_NAME}
    ports:
      - ${HTTP_PORT}:5000
    build:
      context: .
      dockerfile: Dockerfile
  rabbit:
      image: rabbitmq:3-management
      container_name: rabbit
      environment:
        RABBITMQ_DEFAULT_USER: user
        RABBITMQ_DEFAULT_PASS: archbtw
      ports:
        - "15672:15672"
        - "5672:5672"
      networks:
        - rabbitnet
  nifi:
      image: apache/nifi:latest
      container_name: nifi
      environment:
        SINGLE_USER_CREDENTIALS_USERNAME: admin
        SINGLE_USER_CREDENTIALS_PASSWORD: ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      ports:
        - "8443:8443"
      networks:
        - rabbitnet

networks:
  rabbitnet:
