version: "3"

services:
  web:
    container_name: python-${PROJECT_NAME}
    ports:
      - ${HTTP_PORT}:5000
    build:
      context: .
      dockerfile: Dockerfile

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    networks:
      - rabbitnet
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    networks:
      - rabbitnet
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=archbtw

  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - rabbitnet
    ports:
      - "27017:27017"

networks:
  rabbitnet:
    driver: bridge